# Generated by Django 4.0.3 on 2022-04-23 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('event_status', models.CharField(choices=[('UPC', 'UPCOMING'), ('RUN', 'RUNNING'), ('OVR', 'OVER')], default='UPC', max_length=50)),
                ('attendees', models.IntegerField()),
                ('event_date', models.DateField()),
                ('notes', models.TextField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_event', to='client.client')),
                ('contract', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_event', to='contract.contract')),
                ('support_contact', models.ForeignKey(limit_choices_to={'groups__name': 'SupportTeam'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_contact', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
