# Generated by Django 4.0.3 on 2022-04-19 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0002_auto_20220419_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='support_contact',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'SupportTeam'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_contact', to=settings.AUTH_USER_MODEL),
        ),
    ]
